---
efiBootLoader: "grub"
kernel: "/boot/vmlinuz-linux"
img: "/boot/initramfs-linux.img"
fallback: "/boot/initramfs-linux-fallback.img"
timeout: 5
grubInstall: "grub-install"
grubMkconfig: "grub-mkconfig"
