---
efiSystemPartition: "/boot/efi"
userSwapChoices:
  - none
  - small
  - suspend
  - file
initialPartitioningChoice: erase
drawNestedPartitions: true
defaultFileSystemType: "ext4"
availableFileSystemTypes:
  - "ext4"
  - "btrfs"
  - "xfs"
  - "f2fs"
requiredStorage: 16
requiredRam: 2
alwaysShowPartitionLabels: true
