---
defaultGroups:
  - wheel
  - audio
  - video
  - input
  - storage
  - network
  - lp
autologinGroup: autologin
sudoersGroup: wheel
setRootPassword: true
doReusePassword: true
allowWeakPasswords: false
