# services-systemd.conf
# Configures systemd services on the target installed system.
---

units:
  - name: "NetworkManager"
    action: "enable"
  - name: "aisd"
    action: "enable"
  - name: "aios-firstboot"
    action: "enable"
